{
 "title": "KPI Alert dashboard",
 "time": { "from": "2022-10-25T00:00:00.000Z", "to": "2023-05-25T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "device_identifier",
    "label": "Device selector",
    "query": "select distinct device_identifier from kpi_1d\nwhere org_identifier in ($org_identifier);"
   },
   {
    "name": "yearmonth_selector",
    "label": "Year month",
    "query": "select distinct to_char(time, 'YYYY-MM') from kpi_1d\norder by to_char(time, 'YYYY-MM') asc;"
   },
   {
    "name": "org_identifier",
    "label": "Organization",
    "query": "select distinct org_identifier from kpi_1d"
   },
   {
    "name": "kpi_selector",
    "label": "KPI Type",
    "query": "select distinct kpi_type_code \nfrom kpi_1d\nwhere device_identifier in ($device_identifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Perfectly performing devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select *\r\n\r\nfrom (select \r\n\t\t\tto_char(time, 'YYYY-MM') as \"Year month\"\r\n\t\t\t, device_identifier\tas \"Device ID\"\r\n\t\t\t, org_identifier\tas \"Organization ID\"\r\n\t\t\t, sum(kpi_alert_count) as \"Total KPI alerts (per month)\"\r\n\t\t\r\n\t\tfrom kpi_1d\r\n\t\twhere 1=1\r\n\t\tgroup by 1,2,3\r\n\t\torder by sum(kpi_alert_count) asc\r\n\t\t) as data\r\nwhere 1=1\r\n\tand \"Total KPI alerts (per month)\" = 0"
    }
   ]
  },
  {
   "title": "# of observations by alert group per month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "select \r\n\t\r\n\tcount(kpi_alert_count) filter(where kpi_alert_count = 0) as \"Observations without alerts\"\r\n\t, count(kpi_alert_count) filter(where kpi_alert_count > 0) as \"Observations with alerts\"\r\n\t, to_char(time, 'YYYY-MM') as \"Year month\"\t\r\n\r\nfrom kpi_1d\r\nwhere 1=1\r\n\r\n  and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)\r\ngroup by 3\r\norder by to_char(time, 'YYYY-MM') asc"
    }
   ]
  },
  {
   "title": "Observation distribution per conditions",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) filter(where kpi_alert_condition_type_last = 'ABOVE_UPPER_LIMIT') as \"Above upper limit\"\r\n        , count(*) filter(where kpi_alert_condition_type_last = 'NOT_BETWEEN_LOWER_AND_UPPER_LIMIT') as \"In between\"\r\n        , count(*) filter(where kpi_alert_condition_type_last = 'BELOW_LOWER_LIMIT') as \"Below lower limit\"\r\nfrom kpi_1d \r\nwhere 1=1\r\n         and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)"
    }
   ]
  },
  {
   "title": "Unique # of organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct org_identifier)\r\nfrom kpi_1d "
    }
   ]
  },
  {
   "title": "Unique # of devices (per organization)",
   "type": "stat",
   "description": "This also filters per organization",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct device_identifier)\r\nfrom kpi_1d\r\nwhere 1=1\r\n  and org_identifier IN ($org_identifier)"
    }
   ]
  },
  {
   "title": "# of instances 'imperfect' performing devices",
   "type": "stat",
   "description": "This count (grouped by month) how many devices have provided > 0 KPI alerts ",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(total_kpi_alerts) filter(where total_kpi_alerts > 0)\r\n\r\nfrom (select \r\n\t\t\tto_char(time, 'YYYY-MM') as \"Year month\"\r\n\t\t\t, device_identifier\t\r\n\t\t\t, org_identifier\r\n\t\t\t, sum(kpi_alert_count) as total_kpi_alerts\r\n\t\t\r\n\t\tfrom kpi_1d\r\n\t\twhere 1=1\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)\r\n\t\tgroup by 1,2,3\r\n\t\torder by sum(kpi_alert_count) asc\r\n\t\t) as data\r\nwhere 1=1"
    }
   ]
  },
  {
   "title": "KPI alert trend by month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select  avg(kpi_value_min) as \"Minimum KPI value\"\r\n        , avg(kpi_value_max) as \"Maximum KPI value\"\r\n        , avg(kpi_value_last) as \"Average of KPI last value\"\r\n        , date_trunc('month', time) as \"Year month\"\r\n        \r\nfrom kpi_1d \r\nwhere 1=1\r\n        and device_identifier IN ($device_identifier)\r\n        and org_identifier::text in ($org_identifier)\r\n        and kpi_type_code IN ($kpi_selector)\r\n        and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n        \r\n        group by 4"
    }
   ]
  },
  {
   "title": "Device performance based on # of alerts ",
   "type": "piechart",
   "description": "Well performing in this case means that the observation (a device for an organization measuring a specific KPI) has not produced any KPI alerts",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  count(kpi_alert_count) filter(where kpi_alert_count = 0) as \"Well performing observations\"\r\n        , count(kpi_alert_count) filter(where kpi_alert_count > 0) as \"Underperforming observations\"\r\nfrom kpi_1d \r\nwhere 1=1\r\n       and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)"
    }
   ]
  },
  {
   "title": "Total amount of KPI alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(kpi_alert_count) \r\nfrom kpi_1d\r\nwhere 1=1\r\n   and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)"
    }
   ]
  },
  {
   "title": "KPI alert trend by day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select  avg(kpi_value_min) as \"Minimum KPI value\"\r\n        , avg(kpi_value_max) as \"Maximum KPI value\"\r\n        , avg(kpi_value_last) as \"Average of KPI last value\"\r\n        , date_trunc('day', time) as \"Day\"\r\n        \r\nfrom kpi_1d \r\nwhere 1=1\r\n        and device_identifier IN ($device_identifier)\r\n\r\n        and kpi_type_code IN ($kpi_selector)\r\n        and org_identifier::text in ($org_identifier)\r\n        and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n        \r\n        group by 4"
    }
   ]
  },
  {
   "title": "Performance of average KPI last value by KPI code per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n\r\n  AVG(kpi_value_last) as \"Average of last value for\"\r\n  ,kpi_type_code\r\n  ,date_trunc('day', time) as day\r\nFROM\r\n  kpi_1d\r\n  where 1=1\r\n     and to_char(time, 'YYYY-MM') IN ($yearmonth_selector )\r\n  and kpi_type_code IN ($kpi_selector)\r\n\tand device_identifier IN ($device_identifier)\r\n\tand org_identifier IN ($org_identifier)\r\nGROUP BY\r\n  kpi_type_code,\r\n  date_trunc('day', time)"
    }
   ]
  },
  {
   "title": "Top 25 organizations with most # of devices",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "\r\nselect org_identifier::text as metric\r\n, count(distinct device_identifier) as value\r\nfrom kpi_1d\r\nwhere 1=1\r\n  and org_identifier IN ($org_identifier)\r\ngroup by org_identifier\r\norder by count(distinct device_identifier) desc\r\nlimit 25"
    }
   ]
  }
 ]
}